### ISSUE TITLE
Error retrieving topic

### ISSUE THREAD

**Issue by mmittapalli** [pozil/pub-sub-api-java-client#3]
This surely worked before but started to fail now, login connection is successful with given username, password but the next step to retrieve topic is failing with this, any idea?

Aug 17, 2022 4:42:53 PM org.salesforce.demo.PubSubApiClient connect
INFO: PubSub API: connecting to api.pubsub.salesforce.com:7443...
Aug 17, 2022 4:42:54 PM org.salesforce.demo.PubSubApiClient retrieveTopic
INFO: PubSub API: retrieving topic /data/CaseChangeEvent...
Aug 17, 2022 4:42:57 PM org.salesforce.demo.PubSubApiClient main
SEVERE: Failed to retrieve topic /data/CaseChangeEvent: UNAUTHENTICATED: An authentication exception occurred. Provide valid authentication via metadata headers. rpcId: 6cdd3cd5-d289-4cc0-a74b-12f13906514b
org.salesforce.demo.PubSubApiClient$PubSubException: Failed to retrieve topic /data/CaseChangeEvent: UNAUTHENTICATED: An authentication exception occurred. Provide valid authentication via metadata headers. rpcId: 6cdd3cd5-d289-4cc0-a74b-12f13906514b
	at org.salesforce.demo.PubSubApiClient.retrieveTopic(PubSubApiClient.java:83)
	at org.salesforce.demo.PubSubApiClient.retrieveTopicSchema(PubSubApiClient.java:88)
	at org.salesforce.demo.PubSubApiClient.main(PubSubApiClient.java:127)

**Comment by mmittapalli** [comment]
during my debug, I can see session information coming back from sandbox with accessToken, orgId etc and we are setting those on Metadata, so I wonder if this requires any additional header part of Metadata now? is the example still work for you?

**Comment by pozil** [comment]
Hi @mmittapalli. The sample is still working. I just tried it on a new scratch org.

I'm missing some info in your log. Did you see the part that confirms that you're logged in?
```
Logged as xxx@yyy on https://zzzzz.my.salesforce.com
```

**Comment by mmittapalli** [comment]
Yes, these are the preceding log lines for the above log statements

```
Aug 17, 2022 5:41:49 PM org.salesforce.demo.auth.AuthenticationHelper login
INFO: Logged as XXXX@yyyy.com on https://zzzz.my.salesforce.com
```

**Comment by pozil** [comment]
Ok, thanks for confirming. This means that your credentials are valid.
Do you any access rights that could conflict with the view of cases for the current user?
Also is there any firewall or network config that could interfere with the gRPC connection?

**Comment by mmittapalli** [comment]
thanks for response on this, it appears to be the user having had some issue during time accessing the topics though it was logged in. Co-incidentally the user locked out and after resetting the pwd, it started working fully for this flow.
