### ISSUE TITLE
Deserialization returning all unchanged fields as null

### ISSUE THREAD

**Issue by mmittapalli** [pozil/pub-sub-api-java-client#5]
Hi,
payload which is GenericRecord instance within the Event object after parsing, returns all unchanged fields as null, is there any configuration on the DatumReader or other means to avoid this behavior? I am only interested in changed fields being populated part of payload. Below is an example where I changed the credit amount, but rest of the fields have values in SF but comes as null in here.
![Capture](https://user-images.githubusercontent.com/59719251/189552414-539307b3-9ad2-4325-aac2-3728e3487e6f.PNG)

**Comment by pozil** [comment]
Hi @mmittapalli, unfortunately this is part of how Salesforce sends the event payload and Avro's `DatumReader` can't change this.

As mentioned in the readme:
> Note that the event payload includes all object fields but fields that haven't changed are null. Use the values from ChangeEventHeader.nulledFields, ChangeEventHeader.diffFields and ChangeEventHeader.changedFields to identify actual value changes.
